name: Publish ontoRunNER to TestPyPI and PyPI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-publish:
    name: Build and publish ontoRunNER to TestPyPI and PyPI
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2

  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}
      
  - name: Install pypa/build
    run: >-
      python -m
      pip install
      build
      --user

  - name: Build a binary wheel and a source tarball
    run: >-
      python -m
      build
      --sdist
      --wheel
      --outdir dist/
      .